// <auto-generated />
using System;
using CotizacionMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CotizacionMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260713192333_AgregarModuloSeguimientosV2")]
    partial class AgregarModuloSeguimientosV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComentarioNoCotizable")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCotizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("MotivoNoCotizable")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Origen")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegistradoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VendedorAsignadoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Cotizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaMetrosCuadrados")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("CondicionesPago")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroCotizacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("RequiereAutorizacion")
                        .HasColumnType("boolean");

                    b.Property<string>("RutaPdf")
                        .HasColumnType("text");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("LeadId");

                    b.HasIndex("NumeroCotizacion")
                        .IsUnique();

                    b.HasIndex("VendedorId");

                    b.ToTable("Cotizaciones", (string)null);
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorPrimario")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ColorSecundario")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CorreoContacto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EsExclusivaTrane")
                        .HasColumnType("boolean");

                    b.Property<string>("Eslogan")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MonedaBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreLegal")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PlantillaPdfNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("UtilidadEmpresaPorcentaje")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UtilidadVendedorPorcentaje")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CapacidadToneladas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Marca")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MonedaOriginal")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Tecnologia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Instalacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Instalaciones", (string)null);
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.ItemCotizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("CotizacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DescripcionPersonalizada")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UtilidadEmpresaPorcentaje")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UtilidadVendedorPorcentaje")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("EquipoId");

                    b.ToTable("ItemsCotizacion", (string)null);
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.ItemInstalacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CotizacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("InstalacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("InstalacionId");

                    b.ToTable("ItemsInstalacion", (string)null);
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComentarioNoCotizable")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ComentariosInternos")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmpresaCliente")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaContacto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCotizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MotivoNoCotizable")
                        .HasColumnType("integer");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrigenLead")
                        .HasColumnType("integer");

                    b.Property<string>("ProductoBusca")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UltimoSeguimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendedorAsignadoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("VendedorAsignadoId");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Seguimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CotizacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaContacto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<int>("MedioContacto")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ProximoContacto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RecordatorioEnviado")
                        .HasColumnType("boolean");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("LeadId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Seguimientos", (string)null);
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EmpresaUsuario", b =>
                {
                    b.Property<Guid>("EmpresasAccesoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuariosAccesoId")
                        .HasColumnType("uuid");

                    b.HasKey("EmpresasAccesoId", "UsuariosAccesoId");

                    b.HasIndex("UsuariosAccesoId");

                    b.ToTable("EmpresaUsuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Cliente", b =>
                {
                    b.OwnsOne("CotizacionMVC.Models.Valor.Contacto", "Contacto", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Correo")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("NombreContacto")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Telefono")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("TelefonoMovil")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("CotizacionMVC.Models.Valor.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Ciudad")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Colonia")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Estado")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("NumeroExterior")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("NumeroInterior")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Contacto")
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Cotizacion", b =>
                {
                    b.HasOne("CotizacionMVC.Models.Entidades.Cliente", "Cliente")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CotizacionMVC.Models.Entidades.Empresa", "Empresa")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CotizacionMVC.Models.Entidades.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CotizacionMVC.Models.Entidades.Usuario", "Vendedor")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CotizacionMVC.Models.Valor.Dinero", "Iva", b1 =>
                        {
                            b1.Property<Guid>("CotizacionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal?>("TipoCambio")
                                .HasColumnType("numeric");

                            b1.HasKey("CotizacionId");

                            b1.ToTable("Cotizaciones");

                            b1.WithOwner()
                                .HasForeignKey("CotizacionId");
                        });

                    b.OwnsOne("CotizacionMVC.Models.Valor.Dinero", "Subtotal", b1 =>
                        {
                            b1.Property<Guid>("CotizacionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal?>("TipoCambio")
                                .HasColumnType("numeric");

                            b1.HasKey("CotizacionId");

                            b1.ToTable("Cotizaciones");

                            b1.WithOwner()
                                .HasForeignKey("CotizacionId");
                        });

                    b.OwnsOne("CotizacionMVC.Models.Valor.Dinero", "Total", b1 =>
                        {
                            b1.Property<Guid>("CotizacionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal?>("TipoCambio")
                                .HasColumnType("numeric");

                            b1.HasKey("CotizacionId");

                            b1.ToTable("Cotizaciones");

                            b1.WithOwner()
                                .HasForeignKey("CotizacionId");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("Iva")
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Subtotal")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.ItemCotizacion", b =>
                {
                    b.HasOne("CotizacionMVC.Models.Entidades.Cotizacion", "Cotizacion")
                        .WithMany("ItemsEquipos")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CotizacionMVC.Models.Entidades.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CotizacionMVC.Models.Valor.Dinero", "PrecioUnitario", b1 =>
                        {
                            b1.Property<Guid>("ItemCotizacionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal?>("TipoCambio")
                                .HasColumnType("numeric");

                            b1.HasKey("ItemCotizacionId");

                            b1.ToTable("ItemsCotizacion");

                            b1.WithOwner()
                                .HasForeignKey("ItemCotizacionId");
                        });

                    b.OwnsOne("CotizacionMVC.Models.Valor.Dinero", "Subtotal", b1 =>
                        {
                            b1.Property<Guid>("ItemCotizacionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal?>("TipoCambio")
                                .HasColumnType("numeric");

                            b1.HasKey("ItemCotizacionId");

                            b1.ToTable("ItemsCotizacion");

                            b1.WithOwner()
                                .HasForeignKey("ItemCotizacionId");
                        });

                    b.Navigation("Cotizacion");

                    b.Navigation("Equipo");

                    b.Navigation("PrecioUnitario")
                        .IsRequired();

                    b.Navigation("Subtotal")
                        .IsRequired();
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.ItemInstalacion", b =>
                {
                    b.HasOne("CotizacionMVC.Models.Entidades.Cotizacion", "Cotizacion")
                        .WithMany("ItemsInstalacion")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CotizacionMVC.Models.Entidades.Instalacion", "Instalacion")
                        .WithMany()
                        .HasForeignKey("InstalacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("CotizacionMVC.Models.Valor.Dinero", "CostoUnitario", b1 =>
                        {
                            b1.Property<Guid>("ItemInstalacionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal?>("TipoCambio")
                                .HasColumnType("numeric");

                            b1.HasKey("ItemInstalacionId");

                            b1.ToTable("ItemsInstalacion");

                            b1.WithOwner()
                                .HasForeignKey("ItemInstalacionId");
                        });

                    b.OwnsOne("CotizacionMVC.Models.Valor.Dinero", "Subtotal", b1 =>
                        {
                            b1.Property<Guid>("ItemInstalacionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal?>("TipoCambio")
                                .HasColumnType("numeric");

                            b1.HasKey("ItemInstalacionId");

                            b1.ToTable("ItemsInstalacion");

                            b1.WithOwner()
                                .HasForeignKey("ItemInstalacionId");
                        });

                    b.Navigation("CostoUnitario")
                        .IsRequired();

                    b.Navigation("Cotizacion");

                    b.Navigation("Instalacion");

                    b.Navigation("Subtotal")
                        .IsRequired();
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Lead", b =>
                {
                    b.HasOne("CotizacionMVC.Models.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CotizacionMVC.Models.Entidades.Empresa", "Empresa")
                        .WithMany("Leads")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CotizacionMVC.Models.Entidades.Usuario", "VendedorAsignado")
                        .WithMany()
                        .HasForeignKey("VendedorAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("VendedorAsignado");
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Seguimiento", b =>
                {
                    b.HasOne("CotizacionMVC.Models.Entidades.Cotizacion", "Cotizacion")
                        .WithMany("Seguimientos")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CotizacionMVC.Models.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CotizacionMVC.Models.Entidades.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CotizacionMVC.Models.Entidades.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cotizacion");

                    b.Navigation("Empresa");

                    b.Navigation("Lead");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("EmpresaUsuario", b =>
                {
                    b.HasOne("CotizacionMVC.Models.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresasAccesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CotizacionMVC.Models.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosAccesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CotizacionMVC.Models.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CotizacionMVC.Models.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CotizacionMVC.Models.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CotizacionMVC.Models.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Cliente", b =>
                {
                    b.Navigation("Cotizaciones");
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Cotizacion", b =>
                {
                    b.Navigation("ItemsEquipos");

                    b.Navigation("ItemsInstalacion");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Empresa", b =>
                {
                    b.Navigation("Cotizaciones");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("CotizacionMVC.Models.Entidades.Usuario", b =>
                {
                    b.Navigation("Cotizaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
